---
- name: Initial configuration
  hosts: all
  become: true
  vars:
    docker_users:
      - bombel
    bombel_password: "PassboltBombel"

  roles:
    - user
    - packages
    - geerlingguy.docker