---
- name: Initial configuration
  hosts: all
  become: true
  user:
    name: bombel
    password: "{{ 'PassBolt' | password_hash('sha512') }}"
  vars:
    docker_users:
      - bombel

  roles:
    - user
    - packages
    - geerlingguy.docker
      git_repository: "https://github.com/geerlingguy/ansible-role-docker.git"
      git_version: "v4.1.3"