---
- name: create LXC containers
  hosts: all
  become: true  # Użyj sudo/root do wykonywania zadań

  tasks:

    - name: Ustaw zmienną container_name
      set_fact:
        container_name: "test25"

    - name: Create {{ container_name }}
      command: sudo lxc-create -t download -n {{ container_name }} -- -d ubuntu -r focal -a amd64

    - name: Start the LXC container
      lxc_container:
        name: "{{ container_name }}"
        state: started

    - name: Create folder /root/.ssh
      lxc_container:
        name: "{{ container_name }}"
        container_command: "mkdir /root/.ssh"

    - name: Create file authorized_keys with content
      lxc_container:
        name: "{{ container_name }}"
        container_command: echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDmWt18fcbJ7sjnG0177a5vT88mzKJ3DyHr7xslGCE4OaZDhno+QAiJsxtfRyyfZH0+9qbbFNpTOmChQFh5+5OQpunhg7kixpQ4YlWEzJi1xsai8BZgh0Zem78wmVcwKXmcfQXOdHeoiIAdDcxfHCn6S2am+Io+dlRTym5SSFf/yr3CpuAKjLWrEtIP+EKdOLLZvcU2QJEZG1isBOriUVG4lRwTm5LPK82tpP5Qzf3rWG2sSAUXZ9wKeLw/F0MJuJjio6KVPHMxNCo0w+rDraPpvCx9bnjquyBt57MOtKVZYu8sWxeios8pdbj6r3694hwJHaOeUGBkzHzxoeW9r/vUL2gErdDPco/3zfdtE/2bLENGyx/Q0NiJGbA0ZagJLh+8Wo04eHsRIy2gO637cywanZLaeUTA+shpokYkuGSN+ffrAze8Hzh6VHpepHcnkTmgBGf3NmnZQ6x7u1FkcgwmpBsnYIBMK5DnUO7wyWIZDrOHYnC0ltQxaEXcXHYZBX0= root@vagrant" >> /root/.ssh/authorized_keys
    
    - name: Change permission to file authorized_keys
      lxc_container:
        name: "{{ container_name }}"
        container_command: "chmod 600 /root/.ssh/authorized_keys"
    
    - name: update conteiner "{{ container_name }}"
      lxc_container:
        name: "{{ container_name }}"
        container_command: "apt-get update"

    - name: Install openssh-server
      lxc_container:
        name: "{{ container_name }}"
        container_command: "apt-get install openssh-server"
    
    - name: Get the IP address of the LXC container
      shell: lxc-info -i -H -n "{{ container_name }}"
      register: container_ip

    - name: Display the IP address
      debug:
        msg: "The IP address of the LXC container is {{ container_ip.stdout }}"

    - name: Stop the LXC container
      lxc_container:
        name: "{{ container_name }}"
        #state: stopped