---
- name: Install and configure LXC
  hosts: all
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install LXC dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - lxc
        - lxc-templates
        - lxcfs
        - python3-lxc

    - name: Load LXC kernel module
      modprobe:
        name: "{{ item }}"
      with_items:
        - overlay #obsluga warstw plików w kontenerach, zwłaszcza gdy korzysta się z różnych obrazów kontenerów
        - br_netfilter #przydatne w przypadku filtracji nazw kontenerów

    - name: Enable required kernel parameters
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      with_items:
        - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' } #włączenie przekierowania pakietow dla iptables
        - { name: 'net.ipv4.ip_forward', value: '1' } #włączenie przekierowania pakietów IP, umożliwia to kontenerom dostep do sieci zewnetrznej

    - name: Start and enable LXC service
      service:
        name: lxc
        state: started #wystartowanie lxc
        enabled: yes

    - name: Add new file id_rsa
      file:
        path: /root/.ssh/id_rsa
        state: touch
        mode: '0600'

    - name: Add content to file id_rsa
      blockinfile:
        path: /root/.ssh/id_rsa
        block: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcnNhAAAAAwEAAQAAAYEA5lrdfH3Gye7I5xtNe+2ub0/PJsyidw8h6+8bJRghODmmQ4Z6PkAIibMbX0csn2R9Pvam2xTaUzpgoUBYefuTkKbp4YO5IsaUOGJVhMyYtcbGovAWYIdGXpu/MJlXMCl5nH0FznR3qIiAHQ3MXxwp+ktmpviKPnZUU8puUkhX/8q9wqbgCoy1qxLSD/hCnTiy2b3FNkCRGRtYrATq4lFRuJUcE5uSzyvNraT+UM3961htrEgFF2fcCni8PxdDCbiY4qOilTxzMTQqNMPqw62j6bwsfW546rsgbeezDrSlWWLvLFsXoqLPKXW4+q9+veIcCR2jnlBgZMx88aHlva/71C9oBK3Qz3KP9833bRP9myxDRssf0NDYiRmwNGWoCS4fvFqNOHh7ESMtoDut+3MsGp2S2nlEwPrIaaJGJLhkjfn36wM3vB84elR6XqR3J5E5oARn9zZp2UOse7tRZHIMJqQbJ2CATCuQ51Du8MliGQ6zh2JwtJbUMWhF3Fx2GQV9AAAFiCWBKyAlgSsgAAAAB3NzaC1yc2EAAAGBAOZa3Xx9xsnuyOcbTXvtrm9PzybMoncPIevvGyUYITg5pkOGej5ACImzG19HLJ9kfT72ptsU2lM6YKFAWHn7k5Cm6eGDuSLGlDhiVYTMmLXGxqLwFmCHRl6bvzCZVzApeZx9Bc50d6iIgB0NzF8cKfpLZqb4ij52VFPKblJIV//KvcKm4AqMtasS0g/4Qp04stm9xTZAkRkbWKwE6uJRUbiVHBObks8rza2k/lDN/etYbaxIBRdn3Ap4vD8XQwm4mOKjopU8czE0KjTD6sOto+m8LH1ueOq7IG3nsw60pVli7yxbF6Kizyl1uPqvfr3iHAkdo55QYGTMfPGh5b2v+9QvaASt0M9yj/fN920T/ZssQ0bLH9DQ2IkZsDRlqAkuH7xajTh4exEjLaA7rftzLBqdktp5RMD6yGmiRiS4ZI359+sDN7wfOHpUel6kdyeROaAEZ/c2adlDrHu7UWRyDCakGydggEwrkOdQ7vDJYhkOs4dicLSW1DFoRdxcdhkFfQAAAAMBAAEAAAGAFuDdcJjZXoLtxy5KAs33bizCCTt3w1VobBNiYcvEuN3Y6on3qCkZ7/su88aQ4v/LBK7goY+vo2Z/5GQMpYjb/hjlz7USdSa939+8WKUtYZhtcA9iWZH15j2Xvo7sPudPocA1DG062S09dCVDsAqPDMHiXyD+Mff0piHL1TZELy6GrEeApuuUu3nyDQ3+J7lS4hdb9+hvwMubgfI3FeU3tZpxoGzqJtNV6TIi5Amhd3df5SV+A/YXv56AK8/2o4eGz3KHE+sAahHJpymIaV8gn445djlFHPxfxE3+HisMx/qdJ49OwcSgKk0BOtc739EmIvld2OriUEpj9ZJAKyrvc6TccfTitWRyxoCbwEHTommtILPmnPs4bwbLzNMLqqKkeqPMI9wPxkQ1B+xCbO6CGvQPtCU7ngbYmPQJRRAteXhkfk+W9fRLlwQ4M9c9/dcDaBvTOHVU9YRc+2fhTjZEpYcQVwZA671YPh9gvln0nsikXg7DOGpyOfIgjmRaoRSBAAAAwQCAEqJn/RHBouNGabulNp3ZLPTlzV9MpiX9kmQz0tU/71iE+VwGCnMDm+sZbLn9UlI5P5qR8qLX6uSffqLcV5UsV4MJ8Ta177+P6M8ts/ZsUMTa97DnnhcC/iafqfnGnBfpT8Y3elZ6eKlN3n4JAKHui8fcxc37a1mlcZnlqv1rUz6OvGYsAHxflCt7cwERMzE64bkO81COcs/hE/gh0FrS1SCyfdAM33Iiu832ZrtAWclw8Iofa4KXS/pezfcgSD4AAADBAPlmlFc8Dkr4ffvpPIeVabY4ZMD/x69FHJoB6DREm8qRJGk2vg78V4I+CWlH8kUawUIvnIRmXkKqS6HWdNj+7awiPCwGuX2zbAHI6+RymBjlCtqsH/sbadks8rP/EVMDJYsW7Pdb2YGk26J/xyQWDBSE2x1o0M0Ij+UsivQ01scpAFwGMdzKYeDWPBoBN36spGpJ9Jm9rS0svhap/LnCJVGYwwrz2yOoIGZALK0rbpXrErFVSmKKle/S4R+rQQSpYQAAAMEA7HNFcbey7XY/CyUwTadtvHfm3jAu9fIIXQMTpaZkw21+sN/nKY/Q21zU+h9ZiYhPZ+NqZhFeZR/cwNxS6EQ+ZEr+qcIVsiOBItdLSw5YZwytBXffgpJBQEv3Ipq4oHIK23lmI0qpaeT/52wgX69IyoE7QB1m4pVWdJ/OQr7XsRx7e8q/kWiFcv8UiVR6GeNkq/IXAbtinLLlHzkGtfPKhcQfWqkjF/v8sqLqO/Weh7Dvgh2eOyu4rPDlIS8uVkWdAAAADHJvb3RAdmFncmFudAECAwQFBg==
          -----END OPENSSH PRIVATE KEY-----
        state: present
        marker: "# {mark} ANSIBLE MANAGED BLOCK"