---
# tasks file for user
- name: Create bombel group
  group: 
    name: bombel 
    state: present

- name: Create bombel user belonging to sudo and bombel groups
  user:
    name: bombel
    shell: /bin/bash
    groups: 
      - bombel
      - sudo

- name: Set bombel user password
  user:
    name: bombel
    password: "$1$some_pla$cMv9GLB.eleWkYCCWMMzH0" #password create with use openssh salt