---
# tasks file for user
- name: Create bombel group
  group: 
    name: bombel 
    state: present
 
- name: Create bombel user belonging to sudo and bombel groups
  user:
    name: bombel
    shell: /bin/bash
    groups: 
      - bombel
      - sudo

- name: Generate encrypted password for bombel user
  ansible.builtin.bcrypt:
    password: "!QAZ2wsx"
    register: encrypted_password

- name: Set bombel user password
  user:
    name: bombel
    password: "{{ encrypted_password.stdout }}"
 
- name: Set authorized key for user bombel copying it from vagrant user
  authorized_key:
    user: bombel
    state: present
    key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"