- name: First playbook
  hosts: local
  connection: local

  tasks:
    #  - name: Create testansible.txt
    #file:
    # path: testansible.txt
    # state: touch
    # mode: '0754'

  - name: Touch again a file, but not update time
    file:
      path: testansible.txt
      state: touch
      mode: '0755'
      modification_time: preserve
      access_time: preserve

  - name: Remove present file
    file:
      path: absent.txt
      state: absent
