- name: First playbook
  hosts: local
  connection: local

  tasks:
  - name: Create testansible.txt
    file:
      path: testansible.txt
      state: touch
      mode: '0754'
#      state: absent #remove file when file in path
#      owner: vagrant
#      group: vagrant
